### ISSUE TITLE
我一直以为这个也是akamai的风控😂

### ISSUE THREAD

**Issue by boerzi** [lktop/kpsdk#1]
原来是kasada的 我看海外例如ugg 等蛮多电商也在用这套

**Comment by lktop** [comment]
> 原来是kasada的 我看海外例如ugg 等蛮多电商也在用这套

https://www.ugg.com/也用了这个吗  我咋没看出来

**Comment by lktop** [comment]
> 原来是kasada的 我看海外例如ugg 等蛮多电商也在用这套
是的是的 很多国外的都在用

**Comment by boerzi** [comment]
https://au.ugg.com/ 这个站在用 😂

**Comment by lktop** [comment]
> https://au.ugg.com/ 这个站在用 😂

是的是的
